<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="OmkarPC" failures="1" tests="5" name="Personal Loan" time="0.068" errors="0" timestamp="2020-05-22T17:56:23 IST">
  <testcase classname="Section18.Day1TestNG" name="demo" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Section18.Day1TestNG.demo(Day1TestNG.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase classname="Section18.Day2" name="pLoan" time="0.0"/>
  <testcase classname="Section18.Day4" name="WebLoginHomeLoan" time="0.0"/>
  <testcase classname="Section18.Day4" name="LoginAPIHomeLoan" time="0.0"/>
  <testcase classname="Section18.Day4" name="MobileLoginHomeLoan" time="0.0"/>
  <testcase classname="Section18.Day1TestNG" name="secondTest" time="0.0">
    <ignored/>
  </testcase> <!-- secondTest -->
</testsuite> <!-- Personal Loan -->
